name         'salderma-sssd'
version      '1.0.0'
author       'Sean Alderman'
license      'Apache2'
project_page 'http://www.udayton.edu'
source  'https://github.com/salderma/puppet-sssd'
summary 'Puppet module for sssd'
description 'This module installs and manages sssd. Check README for details.'
dependency 'puppetlabs/stdlib', '>=2.0.0'
